name: Test Application

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install package in editable mode
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run quickflask command test
        run: |
          quickflask --name testproject --template base > output.log 2>&1
          cat output.log
          grep "Project 'testproject' created successfully" output.log
